In [1]:
import numpy as np
# Least Square Solution

A = np.array([[4,0],
              [0,2],
              [1,1]])

b = np.array([[2,0,11]]).T # transpose to align dimensions

x, residuals, rank, s = np.linalg.lstsq(A,b,rcond=None)

print('Solution :\n',x)

print('Least Square Error: \n',np.sqrt(residuals))

Solution :
 [[1.]
 [2.]]
Least Square Error: 
 [9.16515139]


In [2]:
import numpy as np
# Least Square Solution

A = np.array([[-1,2],
              [2,-3],
              [-1,3]])

b = np.array([[4,1,2]]).T # transpose to align dimensions

x, residuals, rank, s = np.linalg.lstsq(A,b,rcond=None)

print('Solution :\n',x)

print('Least Square Error: \n',np.sqrt(residuals))

Solution :
 [[3.]
 [2.]]
Least Square Error: 
 [3.31662479]


In [3]:
import numpy as np
# Least Square Solution

A = np.array([[2,1],
              [-2,0],
              [2,3]])

b = np.array([[-5,8,1]]).T # transpose to align dimensions

x, residuals, rank, s = np.linalg.lstsq(A,b,rcond=None)

print('Solution :\n',x)

print('Least Square Error: \n',np.sqrt(residuals))

Solution :
 [[-4.]
 [ 3.]]
Least Square Error: 
 [4.36454766e-16]


In [4]:
import numpy as np
# Least Square Solution

A = np.array([[1,-2],
              [-1,2],
              [0,3],
              [2,5]])

b = np.array([[3,1,-4,2]]).T # transpose to align dimensions

x, residuals, rank, s = np.linalg.lstsq(A,b,rcond=None)

print('Solution :\n',x)

print('Least Square Error: \n',np.sqrt(residuals))

Solution :
 [[ 1.33333333]
 [-0.33333333]]
Least Square Error: 
 [4.47213595]


In [5]:
import numpy as np
# Least Square Solution

A = np.array([[1,3],
              [1,-1],
              [1,1]])

b = np.array([[5,1,0]]).T # transpose to align dimensions

x, residuals, rank, s = np.linalg.lstsq(A,b,rcond=None)

print('Solution :\n',x)

print('Least Square Error: \n',np.sqrt(residuals))

Solution :
 [[1.]
 [1.]]
Least Square Error: 
 [2.44948974]


In [6]:
import numpy as np
# Least Square Solution

A = np.array([[1,1,0],
              [1,1,0],
              [1,0,1],
              [1,0,1]])

b = np.array([[1,3,8,2]]).T # transpose to align dimensions

x, residuals, rank, s = np.linalg.lstsq(A,b,rcond=None)

print('Solution :\n',x)

print('Least Square Error: \n',np.sqrt(residuals))

Solution :
 [[ 2.33333333]
 [-0.33333333]
 [ 2.66666667]]
Least Square Error: 
 []


In [7]:
import numpy as np
# Least Square Solution

A = np.array([[1,1,0],
              [1,1,0],
              [1,1,0],
              [1,0,1],
              [1,0,1],
              [1,0,1]])

b = np.array([[7,2,3,6,5,4]]).T # transpose to align dimensions

x, residuals, rank, s = np.linalg.lstsq(A,b,rcond=None)

print('Solution :\n',x)

print('Least Square Error: \n',np.sqrt(residuals))

Solution :
 [[3.]
 [1.]
 [2.]]
Least Square Error: 
 []


In [8]:
import numpy as np
# Least Square Solution

A = np.array([[1,5],
              [3,1],
              [-2,4]])

b = np.array([[4,-2,-3]]).T # transpose to align dimensions

x, residuals, rank, s = np.linalg.lstsq(A,b,rcond=None)

print('Solution :\n',x)

print('Least Square Error: \n',np.sqrt(residuals))

Solution :
 [[0.28571429]
 [0.14285714]]
Least Square Error: 
 [5.19615242]


In [9]:
import numpy as np
# Least Square Solution

A = np.array([[1,2],
              [-1,4],
              [1,2]])

b = np.array([[3,-1,5]]).T # transpose to align dimensions

x, residuals, rank, s = np.linalg.lstsq(A,b,rcond=None)

print('Solution :\n',x)

print('Least Square Error: \n',np.sqrt(residuals))

Solution :
 [[3. ]
 [0.5]]
Least Square Error: 
 [1.41421356]


In [10]:
import numpy as np
import sympy as sym
# Least Square Solution

A = np.array([[4,0,1],
              [1,-5,1],
              [6,1,0],
              [1,-1,-5]])

b = np.array([[9,0,0,0]]).T# transpose to align dimensions


x, residuals, rank, s = np.linalg.lstsq(A,b,rcond=None)

print('Solution :\n',x)

print('Least Square Error: \n',np.sqrt(residuals))

Solution :
 [[ 6.66666667e-01]
 [-5.55111512e-17]
 [ 3.33333333e-01]]
Least Square Error: 
 [7.34846923]


In [11]:
import numpy as np
# Least Square Solution

A = np.array([[1,1,0],
              [1,0,-1],
              [0,1,1],
              [-1,1,-1]])

b = np.array([[2,5,6,6]]).T # transpose to align dimensions

x, residuals, rank, s = np.linalg.lstsq(A,b,rcond=None)

print('Solution :\n',x)

print('Least Square Error: \n',np.sqrt(residuals))

Solution :
 [[ 0.33333333]
 [ 4.66666667]
 [-1.66666667]]
Least Square Error: 
 [5.19615242]


In [12]:
A = np.array([[3,4],
              [-2,1],
              [3,4]])

b = np.array([[11],
             [-9],
             [5]])

u = np.array([[5],
             [-1]])

v = np.array([[5],
             [-2]])

print("Au =\n",np.matmul(A, u))
print("Av =\n",np.matmul(A, v))

x, residuals, rank, s = np.linalg.lstsq(A,b,rcond=None)

print('Solution :\n',x)

print('Least Square Error: \n',np.sqrt(residuals))

Au =
 [[ 11]
 [-11]
 [ 11]]
Av =
 [[  7]
 [-12]
 [  7]]
Solution :
 [[ 4.]
 [-1.]]
Least Square Error: 
 [4.24264069]


In [13]:
import numpy as np
# Least Square Solution

R =  np.array([[3,5],
               [0,1]])

b = np.array([[7,3,1]]).T # transpose to align dimensions

Q = np.array([[2/3,-1/3],
             [2/3,2/3],
             [1/3,-2/3]]).T

b = np.dot(Q,b)

x, residuals, rank, s = np.linalg.lstsq(R,b,rcond=None)

print('Solution :\n',x)

Solution :
 [[ 4.]
 [-1.]]


In [14]:
import numpy as np
# Least Square Solution

R =  np.array([[2,3],
               [0,5]])

b = np.array([[-1,6,5,7]]).T # transpose to align dimensions

Q = np.array([[1/2,-1/2],
              [1/2,1/2],
              [1/2,-1/2],
              [1/2,1/2]]).T

b = np.dot(Q,b)

x, residuals, rank, s = np.linalg.lstsq(R,b,rcond=None)

print('Solution :\n',x)

Solution :
 [[2.9]
 [0.9]]
