# Orthonormal Vectors

In [1]:
import numpy as np
import sympy as sym

v1=[3,0,-1]
v2=[8,5,-6]

u1=v1

e1=u1/np.sqrt(np.dot(u1,u1))

pv2=(np.dot(u1,v2)/np.dot(u1,u1))

u2=v2-np.dot(pv2,u1)

e2=u2/np.sqrt(np.dot(u2,u2))

print("Orthonormal basis",e1 ,e2)

Orthonormal basis [ 0.9486833   0.         -0.31622777] [-0.16903085  0.84515425 -0.50709255]


In [2]:
import numpy as np
import sympy as sym

v1=[0,4,2]
v2=[5,6,-7]

u1=v1

e1=u1/np.sqrt(np.dot(u1,u1))

pv2=(np.dot(u1,v2)/np.dot(u1,u1))

u2=v2-np.dot(pv2,u1)

e2=u2/np.sqrt(np.dot(u2,u2))

print(e1)
print(e2)

[0.         0.89442719 0.4472136 ]
[ 0.48795004  0.39036003 -0.78072006]


In [3]:
import numpy as np
import sympy as sym

v1=[2,-5,1]
v2=[4,-1,2]

u1=v1

e1=u1/np.sqrt(np.dot(u1,u1))

pv2=(np.dot(u1,v2)/np.dot(u1,u1))

u2=v2-np.dot(pv2,u1)

e2=u2/np.sqrt(np.dot(u2,u2))

print(e1)
print(e2)

[ 0.36514837 -0.91287093  0.18257419]
[0.81649658 0.40824829 0.40824829]


In [4]:
import numpy as np
import sympy as sym

v1=[3,-4,5]
v2=[-3,14,-7]

u1=v1

e1=u1/np.sqrt(np.dot(u1,u1))

pv2=(np.dot(u1,v2)/np.dot(u1,u1))

u2=v2-np.dot(pv2,u1)

e2=u2/np.sqrt(np.dot(u2,u2))

print(e1)
print(e2)

[ 0.42426407 -0.56568542  0.70710678]
[0.40824829 0.81649658 0.40824829]


In [5]:
import numpy as np
import sympy as sym

v1=[1,-4,0,1]
v2=[7,-7,-4,1]

u1=v1

e1=u1/np.sqrt(np.dot(u1,u1))

pv2=(np.dot(u1,v2)/np.dot(u1,u1))

u2=v2-np.dot(pv2,u1)

e2=u2/np.sqrt(np.dot(u2,u2))

print(e1)
print(e2)

[ 0.23570226 -0.94280904  0.          0.23570226]
[ 0.76249285  0.15249857 -0.60999428 -0.15249857]


In [6]:
import numpy as np
import sympy as sym

v1=[3,-1,2,-1]
v2=[-5,9,-9,3]

u1=v1

e1=u1/np.sqrt(np.dot(u1,u1))

pv2=(np.dot(u1,v2)/np.dot(u1,u1))

u2=v2-np.dot(pv2,u1)

e2=u2/np.sqrt(np.dot(u2,u2))



print(e1)
print(e2)

[ 0.77459667 -0.25819889  0.51639778 -0.25819889]
[ 0.51214752  0.76822128 -0.38411064  0.        ]


# Orthogonal Vectors for column space

In [7]:
A=[[3,-5,1],
  [1,1,1],
  [-1,5,-2],
  [3,-7,8]]

B,i= sym.Matrix(A).rref()

C=np.array(A)[:,i]

v1=C[:,0]
v2=C[:,1]
v3=C[:,2]


u1=v1

e1=u1/np.sqrt(np.dot(u1,u1))



pv2u1= np.dot(u1,v2)/np.dot(u1,u1)

u2=v2-np.dot(pv2u1,u1)

e2=u2/np.sqrt(np.dot(u2,u2))




pv3u1= np.dot(u1,v3)/np.dot(u1,u1)

pv3u2= np.dot(u2,v3)/np.dot(u2,u2)

u3=v3-np.dot(pv3u1,u1)-np.dot(pv3u2,u2)

e3=u3/np.sqrt(np.dot(u3,u3))

print(u1)
print(u2)
print(u3)

[ 3  1 -1  3]
[ 1.  3.  3. -1.]
[-3.  1.  1.  3.]


In [8]:
A=[[-1,6,6],
  [3,-8,3],
  [1,-2,6],
  [1,-4,-3]]

B,i= sym.Matrix(A).rref()

C=np.array(A)[:,i]

v1=C[:,0]
v2=C[:,1]
v3=C[:,2]


u1=v1

e1=u1/np.dot(u1,u1)




pv2u1= np.dot(u1,v2)/np.dot(u1,u1)

u2=v2-np.dot(pv2u1,u1)

e2=u2/np.sqrt(np.dot(u2,u2))




pv3u1= np.dot(u1,v3)/np.dot(u1,u1)

pv3u2= np.dot(u2,v3)/np.dot(u2,u2)

u3=v3-np.dot(pv3u1,u1)-np.dot(pv3u2,u2)

e3=u3/np.sqrt(np.dot(u3,u3))


print(u1)
print(u2)
print(u3)

[-1  3  1  1]
[ 3.  1.  1. -1.]
[-1. -1.  3. -1.]


In [9]:
A=[[1,2,5],
  [-1,1,-4],
  [-1,4,-3],
  [1,-4,7],
  [1,2,1]]

B,i= sym.Matrix(A).rref()

C=np.array(A)[:,i]

v1=C[:,0]
v2=C[:,1]
v3=C[:,2]


u1=v1

e1=u1/np.dot(u1,u1)




pv2u1= np.dot(u1,v2)/np.dot(u1,u1)

u2=v2-np.dot(pv2u1,u1)

e2=u2/np.sqrt(np.dot(u2,u2))




pv3u1= np.dot(u1,v3)/np.dot(u1,u1)

pv3u2= np.dot(u2,v3)/np.dot(u2,u2)

u3=v3-np.dot(pv3u1,u1)-np.dot(pv3u2,u2)

e3=u3/np.sqrt(np.dot(u3,u3))


print(u1)
print(u2)
print(u3)

[ 1 -1 -1  1  1]
[ 3.  0.  3. -3.  3.]
[ 2.  0.  2.  2. -2.]


In [10]:
A=[[1,3,5],
  [-1,-3,1],
  [0,2,3],
  [1,5,2],
  [1,5,8]]

B,i= sym.Matrix(A).rref()

C=np.array(A)[:,i]

v1=C[:,0]
v2=C[:,1]
v3=C[:,2]


u1=v1

e1=u1/np.dot(u1,u1)




pv2u1= np.dot(u1,v2)/np.dot(u1,u1)

u2=v2-np.dot(pv2u1,u1)

e2=u2/np.sqrt(np.dot(u2,u2))




pv3u1= np.dot(u1,v3)/np.dot(u1,u1)

pv3u2= np.dot(u2,v3)/np.dot(u2,u2)

u3=v3-np.dot(pv3u1,u1)-np.dot(pv3u2,u2)

e3=u3/np.sqrt(np.dot(u3,u3))


print(u1)
print(u2)
print(u3)

[ 1 -1  0  1  1]
[-1.  1.  2.  1.  1.]
[ 3.  3.  0. -3.  3.]


# QR Decomposition

In [11]:
A=[[5,9],
  [1,7],
  [-3,-5],
  [1,5]]
A=sym.Matrix(A)
Q=[[5/6,-1/6],
  [1/6,5/6],
  [-3/6,1/6],
  [1/6,3/6]]
Q=sym.Matrix(Q)

print("(Q.T)Q=I\n\n",np.matmul(Q.T,Q))

R=np.matmul(Q.T,A)

print("\n\nR=\n",R)

print("\n\nMatrix A=\n\n",np.array(A))

print("\n\nA=QR\n\n",np.matmul(Q,R))

(Q.T)Q=I

 [[1.00000000000000 0]
 [0 1.00000000000000]]


R=
 [[6.00000000000000 12.0000000000000]
 [1.11022302462516e-16 6.00000000000000]]


Matrix A=

 [[5 9]
 [1 7]
 [-3 -5]
 [1 5]]


A=QR

 [[5.00000000000000 9.00000000000000]
 [1.00000000000000 7.00000000000000]
 [-3.00000000000000 -5.00000000000000]
 [1.00000000000000 5.00000000000000]]


In [12]:
A=[[-2,3],
  [5,7],
  [2,-2],
  [4,6]]
A=sym.Matrix(A)
Q=[[-2/7,5/7],
  [5/7,2/7],
  [2/7,-4/7],
  [4/7,2/7]]
Q=sym.Matrix(Q)

print("(Q.T)Q=I\n\n",np.matmul(Q.T,Q))

R=np.matmul(Q.T,A)

print("\n\nR=\n",R)

print("\n\nMatrix A=\n\n",np.array(A))

print("\n\nA=QR\n\n",np.matmul(Q,R))

(Q.T)Q=I

 [[1.00000000000000 0]
 [0 1.00000000000000]]


R=
 [[7.00000000000000 7.00000000000000]
 [-2.22044604925031e-16 7.00000000000000]]


Matrix A=

 [[-2 3]
 [5 7]
 [2 -2]
 [4 6]]


A=QR

 [[-2.00000000000000 3.00000000000000]
 [5.00000000000000 7.00000000000000]
 [2.00000000000000 -2.00000000000000]
 [4.00000000000000 6.00000000000000]]
