In [9]:
#Matrix().rref()

import sympy as sym

sympy.Matrix([[1,2,3],[2,3,4]]).rref()

Object `rref` not found.


(Matrix([
 [1, 0, -1],
 [0, 1,  2]]),
 (0, 1))

In [1]:
# Reduced Row echelon

import sympy as sym

A = ([[8,-4,-7,9], [-4,3,6,-4],[-3,-2,-5,-4],[9,-8,-18,7]])


B,i = sym.Matrix(A).rref()

print("\nReduced Row Echelon Form: \n",B)

print("\nPivotal Columns: \n",i)


Reduced Row Echelon Form: 
 Matrix([[1, 0, 0, 1], [0, 1, 0, -2], [0, 0, 1, 1], [0, 0, 0, 0]])

Pivotal Columns: 
 (0, 1, 2)


In [2]:
# Reduced Row Echelon form

import sympy as sym

import numpy as np

A = [[1,-3,4,-2,5,4],[2,-6,9,-1,8,2],[2,-6,9,-1,9,7],[-1,3,-4,2,-5,-4]]

B,i = sym.Matrix(A).rref()

print(B)

print(i)

print(len(i))

# Row Space of A

R = np.array(B)

print("\nRow Space: \n",R[:len(i),:])

# Column space of A

C = np.array(A)

print("\nColumn Space of A: \n",C[:,i])
B

Matrix([[1, -3, 0, -14, 0, -37], [0, 0, 1, 3, 0, 4], [0, 0, 0, 0, 1, 5], [0, 0, 0, 0, 0, 0]])
(0, 2, 4)
3

Row Space: 
 [[1 -3 0 -14 0 -37]
 [0 0 1 3 0 4]
 [0 0 0 0 1 5]]

Column Space of A: 
 [[ 1  4  5]
 [ 2  9  8]
 [ 2  9  9]
 [-1 -4 -5]]


Matrix([
[1, -3, 0, -14, 0, -37],
[0,  0, 1,   3, 0,   4],
[0,  0, 0,   0, 1,   5],
[0,  0, 0,   0, 0,   0]])

In [3]:
# Row Space, Column space

import sympy as sym

import numpy as np

A = [[-2,-5,8,0,-17],[1,3,-5,1,5],[3,11,-19,7,1],[1,7,-13,5,-3]]

B,i = sym.Matrix(A).rref()

print(B)

print(i)

print(len(i))



# Row Space of A

R = np.array(B)

print("\nRow Space: \n",R[:len(i),:])



# Column space of A

C = np.array(A)

print("\nColumn Space: \n",C[:,i])
B

Matrix([[1, 0, 1, 0, 1], [0, 1, -2, 0, 3], [0, 0, 0, 1, -5], [0, 0, 0, 0, 0]])
(0, 1, 3)
3

Row Space: 
 [[1 0 1 0 1]
 [0 1 -2 0 3]
 [0 0 0 1 -5]]

Column Space: 
 [[-2 -5  0]
 [ 1  3  1]
 [ 3 11  7]
 [ 1  7  5]]


Matrix([
[1, 0,  1, 0,  1],
[0, 1, -2, 0,  3],
[0, 0,  0, 1, -5],
[0, 0,  0, 0,  0]])

In [21]:
# Null space and Left null space

from sympy import Matrix

A = [[-2,-5,8,0,-17],[1,3,-5,1,5],[3,11,-19,7,1],[1,7,-13,5,-3]]

A = Matrix(A)

A * A.nullspace()[0]
print(A)
print("\nNull Space: \n",A.nullspace())
A

Matrix([[-2, -5, 8, 0, -17], [1, 3, -5, 1, 5], [3, 11, -19, 7, 1], [1, 7, -13, 5, -3]])

Null Space: 
 [Matrix([
[-1],
[ 2],
[ 1],
[ 0],
[ 0]]), Matrix([
[-1],
[-3],
[ 0],
[ 5],
[ 1]])]


Matrix([
[-2, -5,   8, 0, -17],
[ 1,  3,  -5, 1,   5],
[ 3, 11, -19, 7,   1],
[ 1,  7, -13, 5,  -3]])

In [18]:
#Transpose of a Matrix

LN = A.T

print(LN)



#Left Null SPace

LN * LN.nullspace()[0]

print("\nLeft Null Space: \n",LN.nullspace())
A

Matrix([[-2, -5, 8, 0, -17], [1, 3, -5, 1, 5], [3, 11, -19, 7, 1], [1, 7, -13, 5, -3]])

Null Space: 
 [Matrix([
[-1],
[ 2],
[ 1],
[ 0],
[ 0]]), Matrix([
[-1],
[-3],
[ 0],
[ 5],
[ 1]])]
Matrix([[-2, 1, 3, 1], [-5, 3, 11, 7], [8, -5, -19, -13], [0, 1, 7, 5], [-17, 5, 1, -3]])

Left Null Space: 
 [Matrix([
[-2],
[-7],
[ 1],
[ 0]])]


Matrix([
[-2, -5,   8, 0, -17],
[ 1,  3,  -5, 1,   5],
[ 3, 11, -19, 7,   1],
[ 1,  7, -13, 5,  -3]])

In [95]:
R = np.array(A2)
print("\nRow Space: \n",R[:len(i),:])


C = np.array(A2)
print("\nColumn Space: \n",C[:,i])
B


Row Space: 
 [[2 -1 1 -6 8]
 [1 -2 -4 3 -2]]

Column Space: 
 [[2 -1]
 [1 -2]
 [-7 8]
 [4 -5]]


Matrix([
[1, 0, 2, -5, 6],
[0, 1, 3, -4, 4],
[0, 0, 0,  0, 0],
[0, 0, 0,  0, 0]])

In [58]:
import numpy as np

from numpy import linalg as lialg



A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])



 # Creating an array

a = np.array([[1, 0], [0, 5]])


print("Array is :",a)


 # calculating an eigen value

 # using eigh() function

c, d = lialg.eig(a)


print("Eigen value is :", c)

print("Eigen vector is :", d)

Array is : [[1 0]
 [0 5]]
Eigen value is : [1. 5.]
Eigen vector is : [[1. 0.]
 [0. 1.]]


In [60]:
# Determinant

 # numpy.linalg.det() method


import numpy as np

A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])



print("\nDeterminant of A:",np.linalg.det(A))


Determinant of A: -306.0


In [2]:
from sympy import Matrix

A = [[-2,-5,8,0,-17],
     [1,3,-5,1,5],
     [3,11,-19,7,1],
     [1,7,-13,5,-3]]

A = Matrix(A)
B,i= sym.Matrix(A1).rref()

ColA=A[:,i]
ColA

NameError: name 'sym' is not defined

In [12]:
A * A.nullspace()[0]
nulA=A.nullspace()
print(nulA)

[Matrix([
[-2],
[-3],
[ 1],
[ 0],
[ 0]]), Matrix([
[5],
[4],
[0],
[1],
[0]]), Matrix([
[-6],
[-4],
[ 0],
[ 0],
[ 1]])]


In [16]:
A=[[2,-1,1,-6,8],
   [1,-2,-4,3,-2],
   [-7,8,10,3,-10],
   [4,-5,-7,0,4]]
B=[[1,-2,-4,3,-2],
    [0,3,9,-12,12],
    [0,0,0,0,0,0],
    [0,0,0,0,0]]
A=Matrix(A)
B,i = sym.Matrix(A).rref()
print("Rank=",len(i))

nulA=A.nullspace()
print(nulA)
print("Dimension of Nul A:",len(A[0,:]),len(nulA))

Rank= 2
[Matrix([
[-2],
[-3],
[ 1],
[ 0],
[ 0]]), Matrix([
[5],
[4],
[0],
[1],
[0]]), Matrix([
[-6],
[-4],
[ 0],
[ 0],
[ 1]])]
Dim of NulA: 5 3
